In [1]:
%%capture
%pip install numpy
%pip install scikit-learn
%pip install pandas

# Questão 1

In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

X, y = load_iris(return_X_y=True)

estrategias = {
    "Zero Rules": "most_frequent",
    "Aleatório Uniforme": "uniform",
    "Aleatório Estratificado": "stratified"
}

sementes = [7, 11]

# Avaliação com acurácia média, desvio e matriz de confusão
def avaliar(strategy, seed):
    modelo = DummyClassifier(strategy=strategy, random_state=seed)
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)

    accs = []
    y_true_total = []
    y_pred_total = []

    for train_idx, test_idx in skf.split(X, y):
        modelo.fit(X[train_idx], y[train_idx])
        y_pred = modelo.predict(X[test_idx])
        acc = accuracy_score(y[test_idx], y_pred)
        accs.append(acc)
        y_true_total.extend(y[test_idx])
        y_pred_total.extend(y_pred)

    media = np.mean(accs)
    desvio = np.std(accs)
    matriz = confusion_matrix(y_true_total, y_pred_total)
    
    return media, desvio, matriz

for nome, strategy in estrategias.items():
    print(f"--- {nome} ---")
    for seed in sementes:
        media, desvio, matriz = avaliar(strategy, seed)
        print(f"Semente {seed} → Acurácia Média: {media:.4f}, Desvio Padrão: {desvio:.4f}")
        print(f"Matriz de Confusão:\n{matriz}\n")

--- Zero Rules ---
Semente 7 → Acurácia Média: 0.3333, Desvio Padrão: 0.0000
Matriz de Confusão:
[[50  0  0]
 [50  0  0]
 [50  0  0]]

Semente 11 → Acurácia Média: 0.3333, Desvio Padrão: 0.0000
Matriz de Confusão:
[[50  0  0]
 [50  0  0]
 [50  0  0]]

--- Aleatório Uniforme ---
Semente 7 → Acurácia Média: 0.3333, Desvio Padrão: 0.0000
Matriz de Confusão:
[[20 20 10]
 [10 10 30]
 [30  0 20]]

Semente 11 → Acurácia Média: 0.2667, Desvio Padrão: 0.0000
Matriz de Confusão:
[[20 30  0]
 [20 20 10]
 [30 20  0]]

--- Aleatório Estratificado ---
Semente 7 → Acurácia Média: 0.2000, Desvio Padrão: 0.0000
Matriz de Confusão:
[[10 30 10]
 [10 20 20]
 [30 20  0]]

Semente 11 → Acurácia Média: 0.4000, Desvio Padrão: 0.0000
Matriz de Confusão:
[[10 10 30]
 [30 20  0]
 [20  0 30]]



# Questão 2

# Questão 3

# Questão 4

# Questão 5

# Questão 6

# Questão 7